# TCL File Generated by Component Editor 18.0
# Fri Oct 04 03:32:04 PDT 2019
# DO NOT MODIFY


# 
# memarbit "memarbit" v1.0
#  2019.10.04.03:32:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module memarbit
# 
set_module_property DESCRIPTION ""
set_module_property NAME memarbit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME memarbit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL memarbit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file memarbit.v VERILOG PATH ../memarbit.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point mem_master
# 
add_interface mem_master conduit end
set_interface_property mem_master associatedClock clock
set_interface_property mem_master associatedReset reset
set_interface_property mem_master ENABLED true
set_interface_property mem_master EXPORT_OF ""
set_interface_property mem_master PORT_NAME_MAP ""
set_interface_property mem_master CMSIS_SVD_VARIABLES ""
set_interface_property mem_master SVD_ADDRESS_GROUP ""

add_interface_port mem_master m_address address Output 18
add_interface_port mem_master m_write write Output 1
add_interface_port mem_master m_read read Output 1
add_interface_port mem_master m_writedata writedata Output 36
add_interface_port mem_master m_readdata readdata Input 36
add_interface_port mem_master m_waitrequest waitrequest Input 1


# 
# connection point mem_slave0
# 
add_interface mem_slave0 conduit end
set_interface_property mem_slave0 associatedClock clock
set_interface_property mem_slave0 associatedReset reset
set_interface_property mem_slave0 ENABLED true
set_interface_property mem_slave0 EXPORT_OF ""
set_interface_property mem_slave0 PORT_NAME_MAP ""
set_interface_property mem_slave0 CMSIS_SVD_VARIABLES ""
set_interface_property mem_slave0 SVD_ADDRESS_GROUP ""

add_interface_port mem_slave0 s0_address address Input 18
add_interface_port mem_slave0 s0_write write Input 1
add_interface_port mem_slave0 s0_read read Input 1
add_interface_port mem_slave0 s0_writedata writedata Input 36
add_interface_port mem_slave0 s0_readdata readdata Output 36
add_interface_port mem_slave0 s0_waitrequest waitrequest Output 1


# 
# connection point mem_slave1
# 
add_interface mem_slave1 conduit end
set_interface_property mem_slave1 associatedClock clock
set_interface_property mem_slave1 associatedReset reset
set_interface_property mem_slave1 ENABLED true
set_interface_property mem_slave1 EXPORT_OF ""
set_interface_property mem_slave1 PORT_NAME_MAP ""
set_interface_property mem_slave1 CMSIS_SVD_VARIABLES ""
set_interface_property mem_slave1 SVD_ADDRESS_GROUP ""

add_interface_port mem_slave1 s1_address address Input 18
add_interface_port mem_slave1 s1_write write Input 1
add_interface_port mem_slave1 s1_read read Input 1
add_interface_port mem_slave1 s1_writedata writedata Input 36
add_interface_port mem_slave1 s1_readdata readdata Output 36
add_interface_port mem_slave1 s1_waitrequest waitrequest Output 1

