# TCL File Generated by Component Editor 18.0
# Tue Dec 03 14:01:27 PST 2019
# DO NOT MODIFY


# 
# memory_256k "memory_256k" v1.0
#  2019.12.03.14:01:27
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module memory_256k
# 
set_module_property DESCRIPTION ""
set_module_property NAME memory_256k
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME memory_256k
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL memory_256k
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file memory_256k_dram.v VERILOG PATH ../memory_256k_dram.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter base_addr STD_LOGIC_VECTOR 805306368 ""
set_parameter_property base_addr DEFAULT_VALUE 805306368
set_parameter_property base_addr DISPLAY_NAME base_addr
set_parameter_property base_addr WIDTH 32
set_parameter_property base_addr TYPE STD_LOGIC_VECTOR
set_parameter_property base_addr UNITS None
set_parameter_property base_addr DESCRIPTION ""
set_parameter_property base_addr HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave conduit end
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 18
add_interface_port slave s_write write Input 1
add_interface_port slave s_read read Input 1
add_interface_port slave s_writedata writedata Input 36
add_interface_port slave s_readdata readdata Output 36
add_interface_port slave s_waitrequest waitrequest Output 1


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset reset
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 0
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master m_address address Output 32
add_interface_port master m_write write Output 1
add_interface_port master m_read read Output 1
add_interface_port master m_writedata writedata Output 64
add_interface_port master m_readdata readdata Input 64
add_interface_port master m_waitrequest waitrequest Input 1

