# TCL File Generated by Component Editor 18.0
# Sun Nov 24 13:36:39 PST 2019
# DO NOT MODIFY


# 
# wcsl_av "wcsl_av" v1.0
#  2019.11.24.13:36:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module wcsl_av
# 
set_module_property DESCRIPTION ""
set_module_property NAME wcsl_av
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME wcsl_av
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL wcsl_av
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file wcsl_av.v VERILOG PATH ../wcsl_av.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point externals
# 
add_interface externals conduit end
set_interface_property externals associatedClock clock
set_interface_property externals associatedReset reset
set_interface_property externals ENABLED true
set_interface_property externals EXPORT_OF ""
set_interface_property externals PORT_NAME_MAP ""
set_interface_property externals CMSIS_SVD_VARIABLES ""
set_interface_property externals SVD_ADDRESS_GROUP ""

add_interface_port externals ctl1 ctl1 Output 18
add_interface_port externals ctl2 ctl2 Output 18
add_interface_port externals ctl3 ctl3 Output 18
add_interface_port externals ctl4 ctl4 Output 18


# 
# connection point fe_s
# 
add_interface fe_s avalon end
set_interface_property fe_s addressUnits WORDS
set_interface_property fe_s associatedClock clock
set_interface_property fe_s associatedReset reset
set_interface_property fe_s bitsPerSymbol 8
set_interface_property fe_s burstOnBurstBoundariesOnly false
set_interface_property fe_s burstcountUnits WORDS
set_interface_property fe_s explicitAddressSpan 0
set_interface_property fe_s holdTime 0
set_interface_property fe_s linewrapBursts false
set_interface_property fe_s maximumPendingReadTransactions 0
set_interface_property fe_s maximumPendingWriteTransactions 0
set_interface_property fe_s readLatency 0
set_interface_property fe_s readWaitStates 0
set_interface_property fe_s readWaitTime 0
set_interface_property fe_s setupTime 0
set_interface_property fe_s timingUnits Cycles
set_interface_property fe_s writeWaitTime 0
set_interface_property fe_s ENABLED true
set_interface_property fe_s EXPORT_OF ""
set_interface_property fe_s PORT_NAME_MAP ""
set_interface_property fe_s CMSIS_SVD_VARIABLES ""
set_interface_property fe_s SVD_ADDRESS_GROUP ""

add_interface_port fe_s s_write write Input 1
add_interface_port fe_s s_address address Input 2
add_interface_port fe_s s_writedata writedata Input 32
set_interface_assignment fe_s embeddedsw.configuration.isFlash 0
set_interface_assignment fe_s embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment fe_s embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment fe_s embeddedsw.configuration.isPrintableDevice 0

