# TCL File Generated by Component Editor 18.0
# Sat Nov 02 04:30:26 PDT 2019
# DO NOT MODIFY


# 
# ka10 "ka10" v1.0
#  2019.11.02.04:30:26
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ka10
# 
set_module_property DESCRIPTION ""
set_module_property NAME ka10
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ka10
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ka10
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ka10.v VERILOG PATH ../ka10.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point iobus_master
# 
add_interface iobus_master conduit end
set_interface_property iobus_master associatedClock clock
set_interface_property iobus_master associatedReset reset
set_interface_property iobus_master ENABLED true
set_interface_property iobus_master EXPORT_OF ""
set_interface_property iobus_master PORT_NAME_MAP ""
set_interface_property iobus_master CMSIS_SVD_VARIABLES ""
set_interface_property iobus_master SVD_ADDRESS_GROUP ""

add_interface_port iobus_master iobus_iob_poweron iob_poweron Output 1
add_interface_port iobus_master iobus_iob_reset iob_reset Output 1
add_interface_port iobus_master iobus_datao_clear datao_clear Output 1
add_interface_port iobus_master iobus_datao_set datao_set Output 1
add_interface_port iobus_master iobus_cono_clear cono_clear Output 1
add_interface_port iobus_master iobus_cono_set cono_set Output 1
add_interface_port iobus_master iobus_iob_fm_datai iob_fm_datai Output 1
add_interface_port iobus_master iobus_iob_fm_status iob_fm_status Output 1
add_interface_port iobus_master iobus_rdi_pulse rdi_pulse Output 1
add_interface_port iobus_master iobus_ios ios Output 7
add_interface_port iobus_master iobus_iob_out iob_write Output 36
add_interface_port iobus_master iobus_pi_req pi_req Input 7
add_interface_port iobus_master iobus_iob_in iob_read Input 36
add_interface_port iobus_master iobus_iob_dr_split dr_split Input 1
add_interface_port iobus_master iobus_rdi_data rdi_data Input 1


# 
# connection point membus_master
# 
add_interface membus_master conduit end
set_interface_property membus_master associatedClock clock
set_interface_property membus_master associatedReset reset
set_interface_property membus_master ENABLED true
set_interface_property membus_master EXPORT_OF ""
set_interface_property membus_master PORT_NAME_MAP ""
set_interface_property membus_master CMSIS_SVD_VARIABLES ""
set_interface_property membus_master SVD_ADDRESS_GROUP ""

add_interface_port membus_master membus_addr_ack addr_ack Input 1
add_interface_port membus_master membus_fmc_select fmc_select Output 1
add_interface_port membus_master membus_ma ma Output 15
add_interface_port membus_master membus_mb_in mb_read Input 36
add_interface_port membus_master membus_mb_out mb_write Output 36
add_interface_port membus_master membus_rd_rq rd_rq Output 1
add_interface_port membus_master membus_rd_rs rd_rs Input 1
add_interface_port membus_master membus_rq_cyc rq_cyc Output 1
add_interface_port membus_master membus_sel sel Output 4
add_interface_port membus_master membus_wr_rq wr_rq Output 1
add_interface_port membus_master membus_wr_rs wr_rs Output 1


# 
# connection point ka10_panel
# 
add_interface ka10_panel conduit end
set_interface_property ka10_panel associatedClock clock
set_interface_property ka10_panel associatedReset reset
set_interface_property ka10_panel ENABLED true
set_interface_property ka10_panel EXPORT_OF ""
set_interface_property ka10_panel PORT_NAME_MAP ""
set_interface_property ka10_panel CMSIS_SVD_VARIABLES ""
set_interface_property ka10_panel SVD_ADDRESS_GROUP ""

add_interface_port ka10_panel key_stop_sw key_stop_sw Input 1
add_interface_port ka10_panel key_exa_sw key_exa_sw Input 1
add_interface_port ka10_panel key_ex_nxt_sw key_ex_nxt_sw Input 1
add_interface_port ka10_panel key_dep_sw key_dep_sw Input 1
add_interface_port ka10_panel key_dep_nxt_sw key_dep_nxt_sw Input 1
add_interface_port ka10_panel key_reset_sw key_reset_sw Input 1
add_interface_port ka10_panel key_exe_sw key_exe_sw Input 1
add_interface_port ka10_panel key_sta_sw key_sta_sw Input 1
add_interface_port ka10_panel key_rdi_sw key_rdi_sw Input 1
add_interface_port ka10_panel key_cont_sw key_cont_sw Input 1
add_interface_port ka10_panel key_sing_inst key_sing_inst Input 1
add_interface_port ka10_panel key_sing_cycle key_sing_cycle Input 1
add_interface_port ka10_panel key_adr_inst key_adr_inst Input 1
add_interface_port ka10_panel key_adr_rd key_adr_rd Input 1
add_interface_port ka10_panel key_adr_wr key_adr_wr Input 1
add_interface_port ka10_panel key_adr_stop key_adr_stop Input 1
add_interface_port ka10_panel key_adr_brk key_adr_brk Input 1
add_interface_port ka10_panel key_par_stop key_par_stop Input 1
add_interface_port ka10_panel key_nxm_stop key_nxm_stop Input 1
add_interface_port ka10_panel key_repeat_sw key_repeat_sw Input 1
add_interface_port ka10_panel ds ds Input 36
add_interface_port ka10_panel as as Input 18
add_interface_port ka10_panel ind_run ind_run Output 1
add_interface_port ka10_panel ind_pi_on ind_pi_on Output 1
add_interface_port ka10_panel pwr_on_ind pwr_on_ind Output 1
add_interface_port ka10_panel ind_prog_stop ind_prog_stop Output 1
add_interface_port ka10_panel ind_user ind_user Output 1
add_interface_port ka10_panel ind_mem_stop ind_mem_stop Output 1
add_interface_port ka10_panel ind_pih ind_pih Output 7
add_interface_port ka10_panel ind_pir ind_pir Output 7
add_interface_port ka10_panel ind_pio ind_pio Output 7
add_interface_port ka10_panel ind_iob_req ind_iob_req Output 7
add_interface_port ka10_panel ind_pc_reg ind_pc_reg Output 18
add_interface_port ka10_panel ind_ir_reg ind_ir_reg Output 18
add_interface_port ka10_panel ind_ma_reg ind_ma_reg Output 18
add_interface_port ka10_panel ind_mi_reg ind_mi_reg Output 36
add_interface_port ka10_panel ind_mi_prog ind_mi_prog Output 1
add_interface_port ka10_panel ind_ar ind_ar Output 7
add_interface_port ka10_panel ind_ar_reg ind_ar_reg Output 36
add_interface_port ka10_panel ind_br_reg ind_br_reg Output 36
add_interface_port ka10_panel ind_mq_reg ind_mq_reg Output 36
add_interface_port ka10_panel ind_ad ind_ad Output 11
add_interface_port ka10_panel ind_ad_reg ind_ad_reg Output 36
add_interface_port ka10_panel ind_sc ind_sc Output 1
add_interface_port ka10_panel ind_sc_reg ind_sc_reg Output 9
add_interface_port ka10_panel ind_fe_reg ind_fe_reg Output 9
add_interface_port ka10_panel ind_scad ind_scad Output 8
add_interface_port ka10_panel ind_scad_reg ind_scad_reg Output 9
add_interface_port ka10_panel ind_ir ind_ir Output 3
add_interface_port ka10_panel ind_key ind_key Output 12
add_interface_port ka10_panel ind_opr ind_opr Output 12
add_interface_port ka10_panel ind_fetch ind_fetch Output 6
add_interface_port ka10_panel ind_store ind_store Output 5
add_interface_port ka10_panel ind_fma ind_fma Output 4
add_interface_port ka10_panel ind_pr_reg ind_pr_reg Output 16
add_interface_port ka10_panel ind_rl_reg ind_rl_reg Output 16
add_interface_port ka10_panel ind_rla_reg ind_rla_reg Output 16
add_interface_port ka10_panel ind_mem ind_mem Output 10
add_interface_port ka10_panel ind_ex ind_ex Output 5
add_interface_port ka10_panel ind_pi ind_pi Output 2
add_interface_port ka10_panel ind_byte ind_byte Output 2
add_interface_port ka10_panel ind_cpa ind_cpa Output 14
add_interface_port ka10_panel ind_misc ind_misc Output 16
add_interface_port ka10_panel ind_nr ind_nr Output 3
add_interface_port ka10_panel ind_as ind_as Output 2
add_interface_port ka10_panel sw_power sw_power Input 1
add_interface_port ka10_panel sc_stop_sw sc_stop_sw Input 1
add_interface_port ka10_panel fm_enable_sw fm_enable_sw Input 1
add_interface_port ka10_panel key_repeat_bypass_sw key_repeat_bypass_sw Input 1
add_interface_port ka10_panel mi_prog_dis_sw mi_prog_dis_sw Input 1
add_interface_port ka10_panel rdi_sel rdi_sel Input 7
     

# 
# connection point fm_slave
# 
add_interface fm_slave conduit end
set_interface_property fm_slave associatedClock clock
set_interface_property fm_slave associatedReset reset
set_interface_property fm_slave ENABLED true
set_interface_property fm_slave EXPORT_OF ""
set_interface_property fm_slave PORT_NAME_MAP ""
set_interface_property fm_slave CMSIS_SVD_VARIABLES ""
set_interface_property fm_slave SVD_ADDRESS_GROUP ""

add_interface_port fm_slave s_address address Input 18
add_interface_port fm_slave s_write write Input 1
add_interface_port fm_slave s_read read Input 1
add_interface_port fm_slave s_writedata writedata Input 36
add_interface_port fm_slave s_readdata readdata Output 36
add_interface_port fm_slave s_waitrequest waitrequest Output 1

