# TCL File Generated by Component Editor 18.0
# Sat Nov 02 12:47:36 PDT 2019
# DO NOT MODIFY


# 
# panel_ka "panel_ka" v1.0
#  2019.11.02.12:47:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module panel_ka
# 
set_module_property DESCRIPTION ""
set_module_property NAME panel_ka
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME panel_ka
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL panel_ka
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file panel_ka.v VERILOG PATH ../panel_ka.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 6
add_interface_port slave s_write write Input 1
add_interface_port slave s_read read Input 1
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ka_panel
# 
add_interface ka_panel conduit end
set_interface_property ka_panel associatedClock clock
set_interface_property ka_panel associatedReset reset
set_interface_property ka_panel ENABLED true
set_interface_property ka_panel EXPORT_OF ""
set_interface_property ka_panel PORT_NAME_MAP ""
set_interface_property ka_panel CMSIS_SVD_VARIABLES ""
set_interface_property ka_panel SVD_ADDRESS_GROUP ""

add_interface_port ka_panel key_sing_inst key_sing_inst Output 1
add_interface_port ka_panel key_sing_cycle key_sing_cycle Output 1
add_interface_port ka_panel key_par_stop key_par_stop Output 1
add_interface_port ka_panel key_nxm_stop key_nxm_stop Output 1
add_interface_port ka_panel key_repeat_sw key_repeat_sw Output 1
add_interface_port ka_panel key_adr_inst key_adr_inst Output 1
add_interface_port ka_panel key_adr_rd key_adr_rd Output 1
add_interface_port ka_panel key_adr_wr key_adr_wr Output 1
add_interface_port ka_panel key_adr_stop key_adr_stop Output 1
add_interface_port ka_panel key_adr_brk key_adr_brk Output 1
add_interface_port ka_panel key_rdi_sw key_rdi_sw Output 1
add_interface_port ka_panel key_sta_sw key_sta_sw Output 1
add_interface_port ka_panel key_cont_sw key_cont_sw Output 1
add_interface_port ka_panel key_stop_sw key_stop_sw Output 1
add_interface_port ka_panel key_reset_sw key_reset_sw Output 1
add_interface_port ka_panel key_exe_sw key_exe_sw Output 1
add_interface_port ka_panel key_exa_sw key_exa_sw Output 1
add_interface_port ka_panel key_ex_nxt_sw key_ex_nxt_sw Output 1
add_interface_port ka_panel key_dep_sw key_dep_sw Output 1
add_interface_port ka_panel key_dep_nxt_sw key_dep_nxt_sw Output 1
add_interface_port ka_panel ds ds Output 36
add_interface_port ka_panel as as Output 18
add_interface_port ka_panel ind_run ind_run Input 1
add_interface_port ka_panel ind_pi_on ind_pi_on Input 1
add_interface_port ka_panel pwr_on_ind pwr_on_ind Input 1
add_interface_port ka_panel ind_prog_stop ind_prog_stop Input 1
add_interface_port ka_panel ind_user ind_user Input 1
add_interface_port ka_panel ind_mem_stop ind_mem_stop Input 1
add_interface_port ka_panel ind_pih ind_pih Input 7
add_interface_port ka_panel ind_pir ind_pir Input 7
add_interface_port ka_panel ind_pio ind_pio Input 7
add_interface_port ka_panel ind_iob_req ind_iob_req Input 7
add_interface_port ka_panel ind_pc_reg ind_pc_reg Input 18
add_interface_port ka_panel ind_ir_reg ind_ir_reg Input 18
add_interface_port ka_panel ind_ma_reg ind_ma_reg Input 18
add_interface_port ka_panel ind_mi_reg ind_mi_reg Input 36
add_interface_port ka_panel ind_mi_prog ind_mi_prog Input 1
add_interface_port ka_panel ind_ar ind_ar Input 7
add_interface_port ka_panel ind_ar_reg ind_ar_reg Input 36
add_interface_port ka_panel ind_br_reg ind_br_reg Input 36
add_interface_port ka_panel ind_mq_reg ind_mq_reg Input 36
add_interface_port ka_panel ind_ad ind_ad Input 11
add_interface_port ka_panel ind_ad_reg ind_ad_reg Input 36
add_interface_port ka_panel ind_sc ind_sc Input 1
add_interface_port ka_panel ind_sc_reg ind_sc_reg Input 9
add_interface_port ka_panel ind_fe_reg ind_fe_reg Input 9
add_interface_port ka_panel ind_scad ind_scad Input 8
add_interface_port ka_panel ind_scad_reg ind_scad_reg Input 9
add_interface_port ka_panel ind_ir ind_ir Input 3
add_interface_port ka_panel ind_key ind_key Input 12
add_interface_port ka_panel ind_opr ind_opr Input 12
add_interface_port ka_panel ind_fetch ind_fetch Input 6
add_interface_port ka_panel ind_store ind_store Input 5
add_interface_port ka_panel ind_fma ind_fma Input 4
add_interface_port ka_panel ind_pr_reg ind_pr_reg Input 16
add_interface_port ka_panel ind_rl_reg ind_rl_reg Input 16
add_interface_port ka_panel ind_rla_reg ind_rla_reg Input 16
add_interface_port ka_panel ind_mem ind_mem Input 10
add_interface_port ka_panel ind_ex ind_ex Input 5
add_interface_port ka_panel ind_pi ind_pi Input 2
add_interface_port ka_panel ind_byte ind_byte Input 2
add_interface_port ka_panel ind_cpa ind_cpa Input 14
add_interface_port ka_panel ind_misc ind_misc Input 16
add_interface_port ka_panel ind_nr ind_nr Input 3
add_interface_port ka_panel ind_as ind_as Input 2
add_interface_port ka_panel sw_power sw_power Output 1
add_interface_port ka_panel sc_stop_sw sc_stop_sw Output 1
add_interface_port ka_panel fm_enable_sw fm_enable_sw Output 1
add_interface_port ka_panel key_repeat_bypass_sw key_repeat_bypass_sw Output 1
add_interface_port ka_panel mi_prog_dis_sw mi_prog_dis_sw Output 1
add_interface_port ka_panel rdi_sel rdi_sel Output 7


# 
# connection point tty_panel
# 
add_interface tty_panel conduit end
set_interface_property tty_panel associatedClock clock
set_interface_property tty_panel associatedReset reset
set_interface_property tty_panel ENABLED true
set_interface_property tty_panel EXPORT_OF ""
set_interface_property tty_panel PORT_NAME_MAP ""
set_interface_property tty_panel CMSIS_SVD_VARIABLES ""
set_interface_property tty_panel SVD_ADDRESS_GROUP ""

add_interface_port tty_panel tty_tti tty_tti Input 8
add_interface_port tty_panel tty_status tty_status Input 10


# 
# connection point ptr_panel
# 
add_interface ptr_panel conduit end
set_interface_property ptr_panel associatedClock clock
set_interface_property ptr_panel associatedReset reset
set_interface_property ptr_panel ENABLED true
set_interface_property ptr_panel EXPORT_OF ""
set_interface_property ptr_panel PORT_NAME_MAP ""
set_interface_property ptr_panel CMSIS_SVD_VARIABLES ""
set_interface_property ptr_panel SVD_ADDRESS_GROUP ""

add_interface_port ptr_panel ptr ptr Input 36
add_interface_port ptr_panel ptr_status ptr_status Input 12
add_interface_port ptr_panel ptr_key_tape_feed ptr_key_tape_feed Output 1


# 
# connection point ptp_panel
# 
add_interface ptp_panel conduit end
set_interface_property ptp_panel associatedClock clock
set_interface_property ptp_panel associatedReset reset
set_interface_property ptp_panel ENABLED true
set_interface_property ptp_panel EXPORT_OF ""
set_interface_property ptp_panel PORT_NAME_MAP ""
set_interface_property ptp_panel CMSIS_SVD_VARIABLES ""
set_interface_property ptp_panel SVD_ADDRESS_GROUP ""

add_interface_port ptp_panel ptp ptp Input 8
add_interface_port ptp_panel ptp_key_tape_feed ptp_key_tape_feed Output 1
add_interface_port ptp_panel ptp_status ptp_status Input 7


# 
# connection point dis_panel
# 
add_interface dis_panel conduit end
set_interface_property dis_panel associatedClock clock
set_interface_property dis_panel associatedReset reset
set_interface_property dis_panel ENABLED true
set_interface_property dis_panel EXPORT_OF ""
set_interface_property dis_panel PORT_NAME_MAP ""
set_interface_property dis_panel CMSIS_SVD_VARIABLES ""
set_interface_property dis_panel SVD_ADDRESS_GROUP ""

add_interface_port dis_panel dis_status dis_status Input 14
add_interface_port dis_panel dis_ib dis_ib Input 36
add_interface_port dis_panel dis_br dis_br Input 18
add_interface_port dis_panel dis_brm dis_brm Input 7
add_interface_port dis_panel dis_x dis_x Input 10
add_interface_port dis_panel dis_y dis_y Input 10
add_interface_port dis_panel dis_s dis_s Input 4
add_interface_port dis_panel dis_i dis_i Input 3
add_interface_port dis_panel dis_mode dis_mode Input 3
add_interface_port dis_panel dis_sz dis_sz Input 2
add_interface_port dis_panel dis_flags dis_flags Input 9
add_interface_port dis_panel dis_fe dis_fe Input 5


# 
# connection point externals
# 
add_interface externals conduit end
set_interface_property externals associatedClock clock
set_interface_property externals associatedReset reset
set_interface_property externals ENABLED true
set_interface_property externals EXPORT_OF ""
set_interface_property externals PORT_NAME_MAP ""
set_interface_property externals CMSIS_SVD_VARIABLES ""
set_interface_property externals SVD_ADDRESS_GROUP ""

add_interface_port externals leds leds Output 8
add_interface_port externals switches switches Input 4
add_interface_port externals ext ext Input 8

