# TCL File Generated by Component Editor 18.0
# Sun Dec 08 14:46:28 PST 2019
# DO NOT MODIFY


# 
# tty_ka10 "tty_ka10" v1.0
#  2019.12.08.14:46:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module tty_ka10
# 
set_module_property DESCRIPTION ""
set_module_property NAME tty_ka10
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tty_ka10
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tty_ka10
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tty.v VERILOG PATH ../tty.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point uart
# 
add_interface uart conduit end
set_interface_property uart associatedClock clock
set_interface_property uart associatedReset reset
set_interface_property uart ENABLED true
set_interface_property uart EXPORT_OF ""
set_interface_property uart PORT_NAME_MAP ""
set_interface_property uart CMSIS_SVD_VARIABLES ""
set_interface_property uart SVD_ADDRESS_GROUP ""

add_interface_port uart rx rx Input 1
add_interface_port uart tx tx Output 1


# 
# connection point tty_panel
# 
add_interface tty_panel conduit end
set_interface_property tty_panel associatedClock clock
set_interface_property tty_panel associatedReset reset
set_interface_property tty_panel ENABLED true
set_interface_property tty_panel EXPORT_OF ""
set_interface_property tty_panel PORT_NAME_MAP ""
set_interface_property tty_panel CMSIS_SVD_VARIABLES ""
set_interface_property tty_panel SVD_ADDRESS_GROUP ""

add_interface_port tty_panel tti_ind tty_tti Output 8
add_interface_port tty_panel status_ind tty_status Output 10


# 
# connection point iobus_slave
# 
add_interface iobus_slave conduit end
set_interface_property iobus_slave associatedClock clock
set_interface_property iobus_slave associatedReset reset
set_interface_property iobus_slave ENABLED true
set_interface_property iobus_slave EXPORT_OF ""
set_interface_property iobus_slave PORT_NAME_MAP ""
set_interface_property iobus_slave CMSIS_SVD_VARIABLES ""
set_interface_property iobus_slave SVD_ADDRESS_GROUP ""

add_interface_port iobus_slave iobus_iob_poweron iob_poweron Input 1
add_interface_port iobus_slave iobus_iob_reset iob_reset Input 1
add_interface_port iobus_slave iobus_datao_clear datao_clear Input 1
add_interface_port iobus_slave iobus_datao_set datao_set Input 1
add_interface_port iobus_slave iobus_cono_clear cono_clear Input 1
add_interface_port iobus_slave iobus_cono_set cono_set Input 1
add_interface_port iobus_slave iobus_iob_fm_datai iob_fm_datai Input 1
add_interface_port iobus_slave iobus_iob_fm_status iob_fm_status Input 1
add_interface_port iobus_slave iobus_rdi_pulse rdi_pulse Input 1
add_interface_port iobus_slave iobus_ios ios Input 7
add_interface_port iobus_slave iobus_iob_in iob_write Input 36
add_interface_port iobus_slave iobus_pi_req pi_req Output 7
add_interface_port iobus_slave iobus_iob_out iob_read Output 36
add_interface_port iobus_slave iobus_dr_split dr_split Output 1
add_interface_port iobus_slave iobus_rdi_data rdi_data Output 1

