# TCL File Generated by Component Editor 18.0
# Wed Apr 07 09:15:13 CEST 2021
# DO NOT MODIFY


# 
# tu56 "tu56" v1.0
#  2021.04.07.09:15:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module tu56
# 
set_module_property DESCRIPTION ""
set_module_property NAME tu56
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tu56
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tu56
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tu56.v VERILOG PATH ../../ka10/tu56.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point DECtape_Controller
# 
add_interface DECtape_Controller conduit end
set_interface_property DECtape_Controller associatedClock clock
set_interface_property DECtape_Controller associatedReset reset
set_interface_property DECtape_Controller ENABLED true
set_interface_property DECtape_Controller EXPORT_OF ""
set_interface_property DECtape_Controller PORT_NAME_MAP ""
set_interface_property DECtape_Controller CMSIS_SVD_VARIABLES ""
set_interface_property DECtape_Controller SVD_ADDRESS_GROUP ""

add_interface_port DECtape_Controller con_go con_go Input 1
add_interface_port DECtape_Controller con_fwd con_fwd Input 1
add_interface_port DECtape_Controller con_rev con_rev Input 1
add_interface_port DECtape_Controller con_all_halt con_all_halt Input 1
add_interface_port DECtape_Controller con_pwr_up_dly con_pwr_up_dly Input 1
add_interface_port DECtape_Controller con_select con_select Input 4
add_interface_port DECtape_Controller con_select_echo con_select_echo Output 1
add_interface_port DECtape_Controller con_wrt_echo con_wrt_echo Output 1
add_interface_port DECtape_Controller con_read con_read Output 5
add_interface_port DECtape_Controller con_write con_write Input 5
add_interface_port DECtape_Controller con_wr con_wr Input 1
add_interface_port DECtape_Controller con_wrtm con_wrtm Input 1
add_interface_port DECtape_Controller con_wrtm_wait con_wrtm_wait Output 1


# 
# connection point externals
# 
add_interface externals conduit end
set_interface_property externals associatedClock clock
set_interface_property externals associatedReset reset
set_interface_property externals ENABLED true
set_interface_property externals EXPORT_OF ""
set_interface_property externals PORT_NAME_MAP ""
set_interface_property externals CMSIS_SVD_VARIABLES ""
set_interface_property externals SVD_ADDRESS_GROUP ""

add_interface_port externals fe_rq fe_rq Output 4


# 
# connection point fe_s
# 
add_interface fe_s avalon end
set_interface_property fe_s addressUnits WORDS
set_interface_property fe_s associatedClock clock
set_interface_property fe_s associatedReset reset
set_interface_property fe_s bitsPerSymbol 8
set_interface_property fe_s burstOnBurstBoundariesOnly false
set_interface_property fe_s burstcountUnits WORDS
set_interface_property fe_s explicitAddressSpan 0
set_interface_property fe_s holdTime 0
set_interface_property fe_s linewrapBursts false
set_interface_property fe_s maximumPendingReadTransactions 0
set_interface_property fe_s maximumPendingWriteTransactions 0
set_interface_property fe_s readLatency 0
set_interface_property fe_s readWaitTime 1
set_interface_property fe_s setupTime 0
set_interface_property fe_s timingUnits Cycles
set_interface_property fe_s writeWaitTime 0
set_interface_property fe_s ENABLED true
set_interface_property fe_s EXPORT_OF ""
set_interface_property fe_s PORT_NAME_MAP ""
set_interface_property fe_s CMSIS_SVD_VARIABLES ""
set_interface_property fe_s SVD_ADDRESS_GROUP ""

add_interface_port fe_s fe_address address Input 1
add_interface_port fe_s fe_read read Input 1
add_interface_port fe_s fe_write write Input 1
add_interface_port fe_s fe_readdata readdata Output 32
add_interface_port fe_s fe_writedata writedata Input 32
set_interface_assignment fe_s embeddedsw.configuration.isFlash 0
set_interface_assignment fe_s embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment fe_s embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment fe_s embeddedsw.configuration.isPrintableDevice 0

