# TCL File Generated by Component Editor 18.0
# Fri Oct 04 08:21:35 PDT 2019
# DO NOT MODIFY


# 
# fast162_dp "fast162_dp" v1.0
#  2019.10.04.08:21:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fast162_dp
# 
set_module_property DESCRIPTION ""
set_module_property NAME fast162_dp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fast162_dp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fast162_dp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fast162_dp.v VERILOG PATH ../fast162_dp.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter memsel_p0 STD_LOGIC_VECTOR 0
set_parameter_property memsel_p0 DEFAULT_VALUE 0
set_parameter_property memsel_p0 DISPLAY_NAME memsel_p0
set_parameter_property memsel_p0 TYPE STD_LOGIC_VECTOR
set_parameter_property memsel_p0 UNITS None
set_parameter_property memsel_p0 ALLOWED_RANGES 0:31
set_parameter_property memsel_p0 HDL_PARAMETER true
add_parameter memsel_p1 STD_LOGIC_VECTOR 0
set_parameter_property memsel_p1 DEFAULT_VALUE 0
set_parameter_property memsel_p1 DISPLAY_NAME memsel_p1
set_parameter_property memsel_p1 TYPE STD_LOGIC_VECTOR
set_parameter_property memsel_p1 UNITS None
set_parameter_property memsel_p1 ALLOWED_RANGES 0:31
set_parameter_property memsel_p1 HDL_PARAMETER true
add_parameter memsel_p2 STD_LOGIC_VECTOR 0
set_parameter_property memsel_p2 DEFAULT_VALUE 0
set_parameter_property memsel_p2 DISPLAY_NAME memsel_p2
set_parameter_property memsel_p2 TYPE STD_LOGIC_VECTOR
set_parameter_property memsel_p2 UNITS None
set_parameter_property memsel_p2 ALLOWED_RANGES 0:31
set_parameter_property memsel_p2 HDL_PARAMETER true
add_parameter memsel_p3 STD_LOGIC_VECTOR 0
set_parameter_property memsel_p3 DEFAULT_VALUE 0
set_parameter_property memsel_p3 DISPLAY_NAME memsel_p3
set_parameter_property memsel_p3 TYPE STD_LOGIC_VECTOR
set_parameter_property memsel_p3 UNITS None
set_parameter_property memsel_p3 ALLOWED_RANGES 0:31
set_parameter_property memsel_p3 HDL_PARAMETER true
add_parameter fmc_p0_sel STD_LOGIC_VECTOR 1
set_parameter_property fmc_p0_sel DEFAULT_VALUE 1
set_parameter_property fmc_p0_sel DISPLAY_NAME fmc_p0_sel
set_parameter_property fmc_p0_sel TYPE STD_LOGIC_VECTOR
set_parameter_property fmc_p0_sel UNITS None
set_parameter_property fmc_p0_sel ALLOWED_RANGES 0:3
set_parameter_property fmc_p0_sel HDL_PARAMETER true
add_parameter fmc_p1_sel STD_LOGIC_VECTOR 0
set_parameter_property fmc_p1_sel DEFAULT_VALUE 0
set_parameter_property fmc_p1_sel DISPLAY_NAME fmc_p1_sel
set_parameter_property fmc_p1_sel TYPE STD_LOGIC_VECTOR
set_parameter_property fmc_p1_sel UNITS None
set_parameter_property fmc_p1_sel ALLOWED_RANGES 0:3
set_parameter_property fmc_p1_sel HDL_PARAMETER true
add_parameter fmc_p2_sel STD_LOGIC_VECTOR 0
set_parameter_property fmc_p2_sel DEFAULT_VALUE 0
set_parameter_property fmc_p2_sel DISPLAY_NAME fmc_p2_sel
set_parameter_property fmc_p2_sel TYPE STD_LOGIC_VECTOR
set_parameter_property fmc_p2_sel UNITS None
set_parameter_property fmc_p2_sel ALLOWED_RANGES 0:3
set_parameter_property fmc_p2_sel HDL_PARAMETER true
add_parameter fmc_p3_sel STD_LOGIC_VECTOR 0
set_parameter_property fmc_p3_sel DEFAULT_VALUE 0
set_parameter_property fmc_p3_sel DISPLAY_NAME fmc_p3_sel
set_parameter_property fmc_p3_sel TYPE STD_LOGIC_VECTOR
set_parameter_property fmc_p3_sel UNITS None
set_parameter_property fmc_p3_sel ALLOWED_RANGES 0:3
set_parameter_property fmc_p3_sel HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mem_slave
# 
add_interface mem_slave conduit end
set_interface_property mem_slave associatedClock clock
set_interface_property mem_slave associatedReset reset
set_interface_property mem_slave ENABLED true
set_interface_property mem_slave EXPORT_OF ""
set_interface_property mem_slave PORT_NAME_MAP ""
set_interface_property mem_slave CMSIS_SVD_VARIABLES ""
set_interface_property mem_slave SVD_ADDRESS_GROUP ""

add_interface_port mem_slave s_address address Input 18
add_interface_port mem_slave s_write write Input 1
add_interface_port mem_slave s_read read Input 1
add_interface_port mem_slave s_writedata writedata Input 36
add_interface_port mem_slave s_readdata readdata Output 36
add_interface_port mem_slave s_waitrequest waitrequest Output 1


# 
# connection point externals
# 
add_interface externals conduit end
set_interface_property externals associatedClock clock
set_interface_property externals associatedReset reset
set_interface_property externals ENABLED true
set_interface_property externals EXPORT_OF ""
set_interface_property externals PORT_NAME_MAP ""
set_interface_property externals CMSIS_SVD_VARIABLES ""
set_interface_property externals SVD_ADDRESS_GROUP ""

add_interface_port externals power power Input 1
add_interface_port externals sw_single_step single_step Input 1
add_interface_port externals sw_restart restart Input 1


# 
# connection point membus_slave_0
# 
add_interface membus_slave_0 conduit end
set_interface_property membus_slave_0 associatedClock clock
set_interface_property membus_slave_0 associatedReset reset
set_interface_property membus_slave_0 ENABLED true
set_interface_property membus_slave_0 EXPORT_OF ""
set_interface_property membus_slave_0 PORT_NAME_MAP ""
set_interface_property membus_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property membus_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port membus_slave_0 membus_addr_ack_p0 addr_ack Output 1
add_interface_port membus_slave_0 membus_fmc_select_p0 fmc_select Input 1
add_interface_port membus_slave_0 membus_ma_p0 ma Input 15
add_interface_port membus_slave_0 membus_mb_in_p0 mb_write Input 36
add_interface_port membus_slave_0 membus_mb_out_p0 mb_read Output 36
add_interface_port membus_slave_0 membus_rd_rq_p0 rd_rq Input 1
add_interface_port membus_slave_0 membus_rd_rs_p0 rd_rs Output 1
add_interface_port membus_slave_0 membus_rq_cyc_p0 rq_cyc Input 1
add_interface_port membus_slave_0 membus_sel_p0 sel Input 4
add_interface_port membus_slave_0 membus_wr_rq_p0 wr_rq Input 1
add_interface_port membus_slave_0 membus_wr_rs_p0 wr_rs Input 1


# 
# connection point membus_slave_1
# 
add_interface membus_slave_1 conduit end
set_interface_property membus_slave_1 associatedClock clock
set_interface_property membus_slave_1 associatedReset reset
set_interface_property membus_slave_1 ENABLED true
set_interface_property membus_slave_1 EXPORT_OF ""
set_interface_property membus_slave_1 PORT_NAME_MAP ""
set_interface_property membus_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property membus_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port membus_slave_1 membus_addr_ack_p1 addr_ack Output 1
add_interface_port membus_slave_1 membus_fmc_select_p1 fmc_select Input 1
add_interface_port membus_slave_1 membus_ma_p1 ma Input 15
add_interface_port membus_slave_1 membus_mb_in_p1 mb_write Input 36
add_interface_port membus_slave_1 membus_mb_out_p1 mb_read Output 36
add_interface_port membus_slave_1 membus_rd_rq_p1 rd_rq Input 1
add_interface_port membus_slave_1 membus_rd_rs_p1 rd_rs Output 1
add_interface_port membus_slave_1 membus_rq_cyc_p1 rq_cyc Input 1
add_interface_port membus_slave_1 membus_sel_p1 sel Input 4
add_interface_port membus_slave_1 membus_wr_rq_p1 wr_rq Input 1
add_interface_port membus_slave_1 membus_wr_rs_p1 wr_rs Input 1


# 
# connection point membus_slave_2
# 
add_interface membus_slave_2 conduit end
set_interface_property membus_slave_2 associatedClock clock
set_interface_property membus_slave_2 associatedReset reset
set_interface_property membus_slave_2 ENABLED true
set_interface_property membus_slave_2 EXPORT_OF ""
set_interface_property membus_slave_2 PORT_NAME_MAP ""
set_interface_property membus_slave_2 CMSIS_SVD_VARIABLES ""
set_interface_property membus_slave_2 SVD_ADDRESS_GROUP ""

add_interface_port membus_slave_2 membus_addr_ack_p2 addr_ack Output 1
add_interface_port membus_slave_2 membus_fmc_select_p2 fmc_select Input 1
add_interface_port membus_slave_2 membus_ma_p2 ma Input 15
add_interface_port membus_slave_2 membus_mb_in_p2 mb_write Input 36
add_interface_port membus_slave_2 membus_mb_out_p2 mb_read Output 36
add_interface_port membus_slave_2 membus_rd_rq_p2 rd_rq Input 1
add_interface_port membus_slave_2 membus_rd_rs_p2 rd_rs Output 1
add_interface_port membus_slave_2 membus_rq_cyc_p2 rq_cyc Input 1
add_interface_port membus_slave_2 membus_sel_p2 sel Input 4
add_interface_port membus_slave_2 membus_wr_rq_p2 wr_rq Input 1
add_interface_port membus_slave_2 membus_wr_rs_p2 wr_rs Input 1


# 
# connection point membus_slave_3
# 
add_interface membus_slave_3 conduit end
set_interface_property membus_slave_3 associatedClock clock
set_interface_property membus_slave_3 associatedReset reset
set_interface_property membus_slave_3 ENABLED true
set_interface_property membus_slave_3 EXPORT_OF ""
set_interface_property membus_slave_3 PORT_NAME_MAP ""
set_interface_property membus_slave_3 CMSIS_SVD_VARIABLES ""
set_interface_property membus_slave_3 SVD_ADDRESS_GROUP ""

add_interface_port membus_slave_3 membus_addr_ack_p3 addr_ack Output 1
add_interface_port membus_slave_3 membus_fmc_select_p3 fmc_select Input 1
add_interface_port membus_slave_3 membus_ma_p3 ma Input 15
add_interface_port membus_slave_3 membus_mb_in_p3 mb_write Input 36
add_interface_port membus_slave_3 membus_mb_out_p3 mb_read Output 36
add_interface_port membus_slave_3 membus_rd_rq_p3 rd_rq Input 1
add_interface_port membus_slave_3 membus_rd_rs_p3 rd_rs Output 1
add_interface_port membus_slave_3 membus_rq_cyc_p3 rq_cyc Input 1
add_interface_port membus_slave_3 membus_sel_p3 sel Input 4
add_interface_port membus_slave_3 membus_wr_rq_p3 wr_rq Input 1
add_interface_port membus_slave_3 membus_wr_rs_p3 wr_rs Input 1

