# TCL File Generated by Component Editor 18.0
# Sat Nov 23 15:52:57 PST 2019
# DO NOT MODIFY


# 
# panel_6 "panel_6" v1.0
#  2019.11.23.15:52:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module panel_6
# 
set_module_property DESCRIPTION ""
set_module_property NAME panel_6
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME panel_6
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL panel_6
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file panel_6.v VERILOG PATH ../panel_6.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 6
add_interface_port slave s_write write Input 1
add_interface_port slave s_read read Input 1
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_waitrequest waitrequest Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point apr_panel
# 
add_interface apr_panel conduit end
set_interface_property apr_panel associatedClock clock
set_interface_property apr_panel associatedReset reset
set_interface_property apr_panel ENABLED true
set_interface_property apr_panel EXPORT_OF ""
set_interface_property apr_panel PORT_NAME_MAP ""
set_interface_property apr_panel CMSIS_SVD_VARIABLES ""
set_interface_property apr_panel SVD_ADDRESS_GROUP ""

add_interface_port apr_panel key_start key_start Output 1
add_interface_port apr_panel key_read_in key_read_in Output 1
add_interface_port apr_panel key_mem_cont key_mem_cont Output 1
add_interface_port apr_panel key_inst_cont key_inst_cont Output 1
add_interface_port apr_panel key_mem_stop key_mem_stop Output 1
add_interface_port apr_panel key_inst_stop key_inst_stop Output 1
add_interface_port apr_panel key_exec key_exec Output 1
add_interface_port apr_panel key_io_reset key_io_reset Output 1
add_interface_port apr_panel key_dep key_dep Output 1
add_interface_port apr_panel key_dep_nxt key_dep_nxt Output 1
add_interface_port apr_panel key_ex key_ex Output 1
add_interface_port apr_panel key_ex_nxt key_ex_nxt Output 1
add_interface_port apr_panel sw_addr_stop sw_addr_stop Output 1
add_interface_port apr_panel sw_mem_disable sw_mem_disable Output 1
add_interface_port apr_panel sw_repeat sw_repeat Output 1
add_interface_port apr_panel datasw datasw Output 36
add_interface_port apr_panel mas mas Output 18
add_interface_port apr_panel sw_rim_maint sw_rim_maint Output 1
add_interface_port apr_panel sw_repeat_bypass sw_repeat_bypass Output 1
add_interface_port apr_panel sw_art3_maint sw_art3_maint Output 1
add_interface_port apr_panel sw_sct_maint sw_sct_maint Output 1
add_interface_port apr_panel sw_split_cyc sw_split_cyc Output 1
add_interface_port apr_panel power power Input 1
add_interface_port apr_panel ir ir Input 18
add_interface_port apr_panel mi mi Input 36
add_interface_port apr_panel ar ar Input 36
add_interface_port apr_panel mb mb Input 36
add_interface_port apr_panel mq mq Input 36
add_interface_port apr_panel pc pc Input 18
add_interface_port apr_panel ma ma Input 18
add_interface_port apr_panel run run Input 1
add_interface_port apr_panel mc_stop mc_stop Input 1
add_interface_port apr_panel pi_active pi_active Input 1
add_interface_port apr_panel pih pih Input 7
add_interface_port apr_panel pir pir Input 7
add_interface_port apr_panel pio pio Input 7
add_interface_port apr_panel pr pr Input 8
add_interface_port apr_panel rlr rlr Input 8
add_interface_port apr_panel rla rla Input 8
add_interface_port apr_panel ff0 ff0 Input 8
add_interface_port apr_panel ff1 ff1 Input 8
add_interface_port apr_panel ff2 ff2 Input 8
add_interface_port apr_panel ff3 ff3 Input 8
add_interface_port apr_panel ff4 ff4 Input 8
add_interface_port apr_panel ff5 ff5 Input 8
add_interface_port apr_panel ff6 ff6 Input 8
add_interface_port apr_panel ff7 ff7 Input 8
add_interface_port apr_panel ff8 ff8 Input 8
add_interface_port apr_panel ff9 ff9 Input 8
add_interface_port apr_panel ff10 ff10 Input 8
add_interface_port apr_panel ff11 ff11 Input 8
add_interface_port apr_panel ff12 ff12 Input 8
add_interface_port apr_panel ff13 ff13 Input 8
add_interface_port apr_panel sw_power sw_power Output 1


# 
# connection point tty_panel
# 
add_interface tty_panel conduit end
set_interface_property tty_panel associatedClock clock
set_interface_property tty_panel associatedReset reset
set_interface_property tty_panel ENABLED true
set_interface_property tty_panel EXPORT_OF ""
set_interface_property tty_panel PORT_NAME_MAP ""
set_interface_property tty_panel CMSIS_SVD_VARIABLES ""
set_interface_property tty_panel SVD_ADDRESS_GROUP ""

add_interface_port tty_panel tty_tti tty_tti Input 8
add_interface_port tty_panel tty_status tty_status Input 7


# 
# connection point ptr_panel
# 
add_interface ptr_panel conduit end
set_interface_property ptr_panel associatedClock clock
set_interface_property ptr_panel associatedReset reset
set_interface_property ptr_panel ENABLED true
set_interface_property ptr_panel EXPORT_OF ""
set_interface_property ptr_panel PORT_NAME_MAP ""
set_interface_property ptr_panel CMSIS_SVD_VARIABLES ""
set_interface_property ptr_panel SVD_ADDRESS_GROUP ""

add_interface_port ptr_panel ptr ptr Input 36
add_interface_port ptr_panel ptr_status ptr_status Input 7
add_interface_port ptr_panel ptr_key_start ptr_key_start Output 1
add_interface_port ptr_panel ptr_key_stop ptr_key_stop Output 1
add_interface_port ptr_panel ptr_key_tape_feed ptr_key_tape_feed Output 1


# 
# connection point ptp_panel
# 
add_interface ptp_panel conduit end
set_interface_property ptp_panel associatedClock clock
set_interface_property ptp_panel associatedReset reset
set_interface_property ptp_panel ENABLED true
set_interface_property ptp_panel EXPORT_OF ""
set_interface_property ptp_panel PORT_NAME_MAP ""
set_interface_property ptp_panel CMSIS_SVD_VARIABLES ""
set_interface_property ptp_panel SVD_ADDRESS_GROUP ""

add_interface_port ptp_panel ptp_key_tape_feed ptp_key_tape_feed Output 1
add_interface_port ptp_panel ptp ptp Input 8
add_interface_port ptp_panel ptp_status ptp_status Input 7


# 
# connection point dis_panel
# 
add_interface dis_panel conduit end
set_interface_property dis_panel associatedClock clock
set_interface_property dis_panel associatedReset reset
set_interface_property dis_panel ENABLED true
set_interface_property dis_panel EXPORT_OF ""
set_interface_property dis_panel PORT_NAME_MAP ""
set_interface_property dis_panel CMSIS_SVD_VARIABLES ""
set_interface_property dis_panel SVD_ADDRESS_GROUP ""

add_interface_port dis_panel dis_status dis_status Input 14
add_interface_port dis_panel dis_ib dis_ib Input 36
add_interface_port dis_panel dis_br dis_br Input 18
add_interface_port dis_panel dis_brm dis_brm Input 7
add_interface_port dis_panel dis_x dis_x Input 10
add_interface_port dis_panel dis_y dis_y Input 10
add_interface_port dis_panel dis_s dis_s Input 4
add_interface_port dis_panel dis_i dis_i Input 3
add_interface_port dis_panel dis_mode dis_mode Input 3
add_interface_port dis_panel dis_sz dis_sz Input 2
add_interface_port dis_panel dis_flags dis_flags Input 9
add_interface_port dis_panel dis_fe dis_fe Input 5


# 
# connection point externals
# 
add_interface externals conduit end
set_interface_property externals associatedClock clock
set_interface_property externals associatedReset reset
set_interface_property externals ENABLED true
set_interface_property externals EXPORT_OF ""
set_interface_property externals PORT_NAME_MAP ""
set_interface_property externals CMSIS_SVD_VARIABLES ""
set_interface_property externals SVD_ADDRESS_GROUP ""

add_interface_port externals leds leds Output 8
add_interface_port externals switches switches Input 4
add_interface_port externals ext ext Input 8

